<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zmm.Domain.Shared\Zmm.Domain.Shared.csproj" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BackgroundJobs" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BackgroundJobs.Domain" Version="$(AbpVersion)" />
  </ItemGroup>
</Project>