<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\Zmm.Application.Contracts\Zmm.Application.Contracts.csproj" />
    <ProjectReference Include="..\Zmm.Domain\Zmm.Domain.csproj" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="$(AbpVersion)" />
  </ItemGroup>

</Project>
